### ISSUE TITLE
Question:: how to get files?

### ISSUE THREAD

**Issue by sT0pe** [doitadrian/react-butterfiles#1]
@doitadrian Is it possible to get files from input after upload?

document.getElementById('selectedFiles').files 

Files array is empty. Is there another way?

**Comment by adrians5j** [comment]
Hi @sT0pe,

not sure what you meant exactly. This component will give you the list of selected files once they are selected (or drag/dropped) and that's it. The upload part is for the developer to implement.

Here's a small example:
https://codesandbox.io/s/recursing-goldstine-ln4nw

**Comment by sT0pe** [comment]
@doitadrian Hi, I mean if there is a way to get files out of component, without saving to redux and context. 
Like default input keep files after upload

**Comment by adrians5j** [comment]
Sorry, the component doesn't contain its own state, it's up to you to save the selection of files in a way that suits your specific need, eg. in your own file upload component.

This component (or rather it's structure) was inspired by [https://github.com/downshift-js/downshift](downshift). It's a low-level component upon which you build your own file selection components for your app (eg. simple file selection button, drag 'n drop, image uploads / galleries etc).   

On one side, yes, you have to build these components yourself, but on the other side, nothing gets in your way. Create your file-related components in the way you want them to work / look, and internally use this lib for all file-selection situations.

**Comment by sT0pe** [comment]
I see, thanks for fast answer!
