### ISSUE TITLE
Incorrect prop in documentation

### ISSUE THREAD

**Issue by readeral** [doitadrian/react-butterfiles#4]
## This is:
- Documentation error

## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior
https://github.com/doitadrian/react-butterfiles#props should have maxSize listed as a prop

## Actual Behavior
incorrectly has maxFileSize

## Possible Solution
Pull request submitted

**Comment by adrians5j** [comment]
Hi, @readeral, sorry for being late.

Nice catch! 

I just noticed `maxFileSize` is also mentioned by the `maxSizeExceeded` error, can you change it there too, please?

We can merge this one then for sure.

Thanks!

**Comment by readeral** [comment]
Done :)

**Comment by adrians5j** [comment]
Fixed by https://github.com/doitadrian/react-butterfiles/pull/2
