### ISSUE TITLE
Wrapping div causes styling limitations

### ISSUE THREAD

**Issue by readeral** [doitadrian/react-butterfiles#5]
## This is:
- Bug
- Feature request

## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior
Passing the `<input>` a grid item property via the getDropZoneProps should result in the `<input>` being laid out upon the grid

## Actual Behavior
Due to to the component's wrapping `<div>`, the `<input>` is not a direct child of a wrapper with the `display: grid` property, and so is not placed on the grid.

## Steps to Reproduce the Problem
1. Place `<Files />` component within a wrapping `<div>` with the css property of `display: grid` and other grid related syntax
2. Pass css props via getDropZoneProps placing the input on a grid (e.g. `grid-column: 1/2`
3. input will not position correctly

## Detailed Description
See pull request

## Possible Solution
See pull request

**Comment by adrians5j** [comment]
Closed by https://github.com/doitadrian/react-butterfiles/pull/3.
